spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cineverse_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

tmdb:
  api-key: 1f54bd990f1cdfb230adb312546d765d

server:
  port: 8081
